language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

notifications:
  email: false

install: yarn

script: yarn build

deploy:
  provider: script
  script: yarn upload
  skip_cleanup: true
  on:
    branch: master